/*
 * Service Provider (swaggercodegen)
 *
 * This service provider allows the creation of fake 'cdns' resources
 *
 * API version: 1.0.0
 * Contact: apiteam@serviceprovider.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"net/http"
	"io/ioutil"
	"os"
	"fmt"
)

func ApiDiscovery(w http.ResponseWriter, r *http.Request) {
	pwd, _ := os.Getwd()
	b, err := ioutil.ReadFile(pwd + "/resources/swagger.yaml")
	if err != nil {
		fmt.Print(err)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write(b)
}

func GetVersion(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
