/*
 * Dummy Service Provider generated using 'swaggercodegen' that has two resources 'cdns' and 'lbs' which are terraform compliant
 *
 * This service provider allows the creation of fake 'cdns' and 'lbs' resources
 *
 * API version: 1.0.0
 * Contact: apiteam@serviceprovider.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type Lbv1 struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	Backends []string `json:"backends"`

	TimeToProcess int32 `json:"timeToProcess"`

	SimulateFailure bool `json:"simulate_failure"`

	// lb resource status
	Status string `json:"status,omitempty"`
}
